meshplus/bitxhub

internal/executor/contracts/interchain.go

when the destination chain id is illegal, bitxhub should ignore it instead of returning error. The appchain which invoked this tx will wait for this tx to timeout.

refactor(executor): refactor illegal tx handling

---

internal/executor/contracts/interchain.go

When the destination chain id of ibtp is not exist in bitxhub, its content should still be processed.
close #22

feat(executor): handling invalid destination chain id

---

internal/ledger/account.go
internal/ledger/blockchain.go
internal/ledger/chain_meta.go
internal/ledger/journal.go
internal/ledger/ledger.go
internal/ledger/state_accessor.go
pkg/order/etcdraft/node.go
pkg/order/etcdraft/txpool/txpool.go
pkg/order/filter.go
pkg/storage/leveldb/leveldb.go
pkg/storage/storage.go

The process panics if DB returns error except errors.ErrNotFound. If DB returns errors.ErrNotFound when it tries to get sth., returns nil data instead.

refactor(*): deal with DB error in storage

---

api/grpc/subscribe.go
internal/router/interchain.go

1. add default tx wrapper for return when a block contains no interchan tx
2. close channel when GetInterchainWrapper and GetBlockHeader finish

feat(api): add default tx wrapper for return

---

pkg/peermgr/swarm.go

Use sync.Map instead of map to make it go routine safe.

fix(*): fix concurrent map write in swarm.go

---

tester/helper.go

Assign transaction hash while deploying contract in test. After this fix, different rules will have different address.

fix(tester): assign transaction hash

---

pkg/order/etcdraft/node.go
pkg/order/mempool/mempool.go
pkg/order/mempool/mempool_impl.go

1. If some transactions are missing when calling the func constructSameBatch by a
follower to construct the same block, avoid persistent this block;
2. Increase the chain height of follower after finishing getting the block from mempool;

fix(mempool): fix two bugs:

---

go.mod
go.sum
pkg/order/etcdraft/node.go
pkg/order/mempool/mempool.go
pkg/order/mempool/mempool_impl.go
pkg/order/mempool/utils.go
tester/case001_api_test.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case005_store_test.go
tester/helper.go

1. If some transactions are missing when calling the func constructSameBatch by a
follower to construct the same block, avoid persistent this block;
2. Increase the chain height of follower after finishing getting the block from mempool;
(cherry picked from commit 5a53cf143504bedf47649c5133b649f2065b5b74)

fix(mempool): fix two mempool bugs:

---

cmd/bitxhub/key.go

fix "btxhub key show" command should return error but not bug

fix(cmd): fix "bitxhub key show" command with wrong path

---

go.mod
go.sum
internal/app/bitxhub.go
internal/executor/executor_test.go
internal/executor/handle.go
pkg/order/config.go
pkg/order/etcdraft/node.go
pkg/order/etcdraft/node_test.go
pkg/order/etcdraft/node_util_test.go
pkg/order/mempool/mempool_impl.go
pkg/order/mempool/mempool_test.go
pkg/order/mempool/mempool_test_util.go
pkg/order/mempool/tx_store.go
pkg/order/mempool/types.go
pkg/order/solo/node.go
pkg/order/solo/node_test.go
pkg/peermgr/mock_peermgr/mock_peermgr.go
tester/case003_interchain_test.go
tester/helper.go
tester/tester_test.go

1. remove ibtp index to sort interchain txs
2. fix a bug that mempool can't work properly after reboot

refactor(mempool): use account nonce to sort transactions

---

pkg/order/mempool/tx_store.go

(cherry picked from commit c897d8c669a88af00115427b92096588efc0c9ce)

fix(mempool): fix concurrent map read and write

---

internal/executor/contracts/rule_manager.go

The objID of rule management is the appchain ID rather than the rule address

fix(*): fix a bug about wrong objid in rule management

---

internal/app/bitxhub.go

1. Add genesis block hash print in log;
2. Fix a bug where exec.currentBlockHash was 0x0 when handling the genesis block

fix(*): add genesis block hash print in log

---

goent.diff
pkg/order/etcdraft/node.go
pkg/order/etcdraft/node_test.go

- Ensure that the number of connected peers reaches Quorum when the order is started.
- feat(rbft): update go mod.

feat(raft): adjust the order start sequence

---

api/jsonrpc/namespaces/eth/api.go

1. support get latest block by number -1
2. treat -2 as latest block (no pending block in bitxhub)

fix(api): support get block by -1 and -2

---

go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/service_manager.go
tester/case008_service_test.go

1. The appchain is unavailable in the logouting state. Therefore, it need to pause the service and unpause service when logouting fails;
2. If the service logout fails, check whether the appchain is available. If the appchain is unavailable, freeze the service.

fix(*): fix bugs in the association between appchain governance and rule governance

---

cmd/bitxhub/client/governance.go

1. Extend the time interval for the first transaction receipt;
2. Delete "error" from logs that do not receive receipt because it is not error.

fix(cmd): fix a log error that the client failed to get tx receipt

---

internal/executor/contracts/service_manager.go

Governance methods are generally returned to a specified format for easy processing

fix(contracts): fix update service return is not a getGovernanceRet

---

cmd/bitxhub/client/dapp_manage.go
go.mod
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/dapp_manager.go
internal/executor/contracts/dapp_manager_test.go
internal/executor/contracts/governance.go
internal/executor/contracts/governance_test.go
internal/executor/contracts/rule_manager.go
internal/executor/contracts/rule_manager_test.go
internal/executor/contracts/service_manager.go
internal/executor/contracts/service_manager_test.go
internal/executor/contracts/trust_chain_test.go
pkg/order/etcdraft/storage_test.go

1. Add bvm unit tests;
2. Improve the CMD of dapp mgr;
3. Fix invocation address error when invoking other contracts in service governance module;
4. Fix an error that the service governance module returned nil when querying the service list.

test(*): add bvm unit tests

---

internal/coreapi/chain.go

- Change nano to second when premo calculate tps

fix: using second to calculating tps

---

cmd/bitxhub/client/node_manage.go
cmd/bitxhub/client/role_manage.go
go.mod
go.sum
internal/executor/contracts/node_manager.go
internal/executor/contracts/node_manager_test.go
internal/executor/contracts/role.go

1. The audit admin is unbound from the audit node only after being logouted successfully;
2. If the audit admin fails to logout, it will be automatically suspended if the audit node becomes unavailable;
3. Fix the bug that panic occurs when bound audit node is logouted.
Bitxhub-core needs to be merged first: meshplus/bitxhub-core#137

fix(*): fix the node management bug

---

internal/executor/contracts/appchain_manager.go
internal/executor/contracts/interchain.go
internal/executor/contracts/interchain_test.go

1. Fix the bug of not checking the availability of the destination service when the source service is not local.
2. Delete the redundant appchain availability check when checking IBTP to reduce cross-contract calls. If a service is available, the appchain must be available, and if a service is not available, the availability of the appchain is irrelevant.
3. Simplify the way of checking the availability of appchain (including relay chain) and service. Instead of returning a Masshal object across a contract call and then unmarshal to fetch the state, the process now returns the state directly across a contract call.
4. Delete the repeated operation on cross-contract call of query destination service info when checking index. The destination service info is already obtained when querying …

fix(bvm): Optimize some redundant cross-contract calls and JSON parsing in interchain contract
