.gitignore
scripts/deploy.sh

add deploy scripts for compiling linux binary and deploying to server

chore(scripts): add deploy bitxhub scripts

---

internal/executor/contracts/interchain.go

Add access control for `DeleteAppchain` and `GetIBTPByID` method

feat(executor): adding access control for interchain contract

---

internal/executor/contracts/interchain.go
internal/executor/executor.go
internal/executor/handle.go
internal/validator/fabric_v14_validator.go
internal/validator/rule_validator.go
internal/validator/validator.go
pkg/vm/boltvm/bolt_stub.go
pkg/vm/boltvm/boltvm.go
pkg/vm/boltvm/stub.go

1. add validation engine
2. now validator will be inited in validation engine, validator type will be choosed by the address

feat(validator): add go internal fabric rule

---

api/grpc/chain.go
api/grpc/info.go
api/grpc/network.go
cmd/bitxhub/client/chain.go
cmd/bitxhub/client/client.go
cmd/bitxhub/client/validators.go
go.mod
go.sum

feat(client): add validators command

---

.github/workflows/build.yml

1. remove secret codecov token
2. update to v1.0.6(codecov-action)

ci(codecov): update to 1.0.6

---

scripts/quick_start/fabric_pier.sh

Rename fabric rule file. Replace hyphen with underline.

fix(srcipt): rename fabric rule file

---

Makefile

Closes https://github.com/meshplus/bitxhub/issues/52

fix(Makefile): Use GOLDFLAGS

---

internal/ledger/account.go
internal/ledger/account_test.go
internal/ledger/journal.go
internal/ledger/ledger.go
internal/ledger/ledger_test.go
internal/ledger/state_accessor.go
internal/ledger/state_accessor_test.go

get prevJournalHash when new ledger

fix(ledger): get prevJournalHash when new ledger

---

internal/ledger/state_accessor.go

Fix concurrent map writes when getting account.

fix(ledger): fix concurrent map writes

---

internal/executor/contracts/interchain.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case006_pier_test.go

Now appchain registration need upload public key.

feat: add register pubkey

---

internal/executor/contracts/interchain.go

Add get public key in interchain.

feat: add get public key

---

internal/ledger/journal.go
internal/ledger/ledger.go
internal/ledger/ledger_test.go
internal/ledger/state_accessor.go
internal/ledger/types.go

refactor(ledger): add interface to remove journal

---

go.mod
go.sum
internal/constant/constant.go
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/interchain.go
internal/executor/contracts/role.go
internal/executor/contracts/rule_manager.go
internal/executor/contracts/store.go
internal/executor/executor.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go

1. remove appchain contract to bitxhub-core project.
2. extract IBTP contract from appchain.

refactor(contracts): remove appchain manager

---

go.mod
go.sum

fix(*): use latest kit

---

internal/executor/executor_test.go

test(executor): fix occasional test hang

---

internal/app/bitxhub.go

1. disable p2p when start bitxhub in solo mode.

fix(solo): disable p2p when start bitxhub in solo mode

---

go.mod
go.sum
tester/case002_appchain_test.go

Add test cases to complete integration test.

test(tester): add test cases

---

internal/app/bitxhub.go

maximize the file descriptor allowance of the process to the maximum hard-limit allowed by the OS

perf(app):raise ulimit

---

scripts/cluster.sh

remove unused command about ulimit in cluster.sh

refactor(scripts):remove unused command in cluster.sh

---

internal/app/bitxhub.go

Add a log which will output the value of ulimit.

perf(app): add log output about ulimit

---

api/grpc/transaction.go
go.mod
go.sum
internal/coreapi/api/api.go
internal/coreapi/broker.go
tester/case001_api_test.go

refactor readonly tx api return type from pb.Response to pb.Receipt

refactor(api): refactor readonly tx api return type

---

go.mod
go.sum

tx signature should be signed by tx.From address

fix(go.mod): fix invalid tx signature got verified

---

docs/deploy/BitXhubv1.0.0规范化部署文档.md

add one part about how to invoke interchain transfer after deployment

docs(docs): revise deploy doc

---

pkg/order/etcdraft/node.go
pkg/order/etcdraft/node_test.go
pkg/order/mempool/mempool.go
pkg/order/mempool/mempool_impl.go
pkg/order/mempool/tx_cache.go
pkg/order/mempool/types.go

1. logger in mempool and txCache passed by Order module instead of loggers
2. fix goroutine not return after receiving signal from close channel in mempool error
3. fix idSlice is not initialized with 0 length in GenerateRaftPeers function

fix(order): fix errors in node_test

---

go.mod
go.sum
pkg/order/mempool/utils.go

(cherry picked from commit 3b844ee7c70782d9a5c489f79cc4f93049689835)

fix(*): use category instead of type

---

api/grpc/transaction.go
config/bitxhub.toml
internal/executor/handle.go
pkg/order/mempool/btree_index.go
pkg/order/mempool/btree_index_test.go
pkg/order/mempool/mempool.go
pkg/order/mempool/mempool_impl.go
pkg/order/mempool/mempool_impl_test.go
pkg/order/mempool/mempool_test.go
pkg/order/mempool/mempool_test_util.go
pkg/order/mempool/storage.go
pkg/order/mempool/storage_test.go
pkg/order/mempool/tx_cache.go
pkg/order/mempool/tx_cache_test.go
pkg/order/mempool/tx_store.go
pkg/order/mempool/tx_store_test.go
pkg/order/mempool/util_test.go
pkg/order/mempool/utils.go

feat(mempool): add comments and unit tests for mempool, and verify the signature in api module instead of mempool.

feat(mempool): add comments and unit tests for mempool, and verify the signature in api module instead of mempool.

---

cmd/bitxhub/start.go
config/bitxhub.toml
internal/repo/config.go
pkg/order/mempool/mempool_impl.go
pkg/order/mempool/mempool_test.go
pkg/order/mempool/util_test.go

feat(pprof): add runtime type for pprof

---

config/bitxhub.toml
go.mod
go.sum
internal/app/bitxhub.go
internal/executor/executor.go
internal/executor/executor_test.go
internal/executor/handle.go
internal/executor/serial_executor.go
internal/repo/config.go
pkg/imports/imports.go
pkg/imports/place.go
pkg/vm/boltvm/boltvm.go
pkg/vm/boltvm/register.go
pkg/vm/boltvm/stub.go

1. Refactor executor to support different transaction executor type
2. Add executor type to config file

refactor(executor): support multi-version of executor

---

internal/executor/executor.go
internal/executor/handle.go

(cherry picked from commit 4be06f3276a787d6dc84f6504b568395619fb19b)

refactor(executor): post block event after block is persisted

---

Makefile

1. remove modfile flag from build and install
2. add buildent and installend

fix(*): update Makefile

---

go.mod
go.sum
goent.mod
internal/executor/executor.go
internal/executor/serial_executor.go
pkg/proof/proof_pool.go

1. Add logger argument to serial executor constructor
2. Change log level from error to warn when IBTP checking fails

refactor(*): add executor logger to serial executor

---

cmd/bitxhub/key.go
go.mod

fix "btxhub key show" command should return error but not bug

fix(cmd): fix "bitxhub key show" command with wrong path

---

pkg/order/etcdraft/node.go
pkg/order/etcdraft/txpool/txpool.go

add some logs for txpool and delete the executing check on proposal gorutine.

fix(txpool): add some logs for txpool and delete the executing check on proposal gorutine.

---

Makefile
pkg/order/solo/config.go
pkg/order/solo/node.go
pkg/order/solo/node_test.go

1. add mempool module to solo plugin and its unit test
2. add solo related starting scripts and config files

feat(solo): add mempool for solo plugin

---

internal/executor/executor.go
internal/executor/handle.go

Change some info level logs to debug level in module executor.

refactor(executor): adjust log level

---

go.mod
go.sum

Add custom methods to marshal `types.Hash` and `types.Address`

build: update kit

---

go.mod
go.sum
internal/app/feedhub.go
internal/executor/executor.go
internal/executor/executor_test.go
internal/executor/handle.go
internal/executor/types.go
pkg/order/etcdraft/node.go
pkg/order/etcdraft/node_test.go
pkg/order/order.go
pkg/order/solo/node.go
pkg/order/solo/node_test.go
pkg/peermgr/mock_peermgr/mock_peermgr.go

…e unmber of signature verifications

perf(*): add localList to mark the txs received from api to reduce the number of signature verifications.

---

scripts/prepare.sh

Add script to automatically installs the tmux with package manager based on the system type, both linux and macos are supported

fix issue #24

---

.github/workflows/notify.yml

ci: add notice on Dingding when there is a pr opened

---

Makefile
scripts/release_binary.sh

fix(ci):get app_version automatically

---

go.sum
pkg/order/mempool/tx_store.go

keep only one item txLiveTimeMap for each account and nonce pair.

fix(mempool): fix panic in shardTxList

---

internal/executor/executor_test.go
internal/ledger/types.go
pkg/order/mempool/mempool.go
pkg/order/mempool/mempool_impl.go
pkg/order/mempool/tx_store.go
pkg/peermgr/mock_peermgr/mock_peermgr.go

1. fix mempool panic when getting nonce concurrently
2. pass unit test

fix(mempool): fix concurrent map read and write

---

cmd/bitxhub/client/rule_manage.go
go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/rule_manager.go
pkg/peermgr/mock_peermgr/mock_peermgr.go
tester/case004_role_test.go

1. Fix the bug that changes the state of the managed object when submitting a proposal fails;
2. Add interface to get rule state.

fix(*): fix bugs about governance

---

internal/executor/contracts/governance.go
internal/executor/contracts/governance_test.go

Priority invalidation due to a wrong object ID in rule governance.

fix(contracts): fix a bug where the proposal priority in rule governance was not valid

---

cmd/bitxhub/client/appchain_manage.go
cmd/bitxhub/client/governance.go
cmd/bitxhub/client/rule_manage.go
config/bitxhub.toml
go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/governance.go
internal/executor/contracts/role.go
internal/executor/contracts/role_test.go
internal/executor/contracts/rule_manager.go
internal/executor/contracts/rule_manager_test.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case006_vote_test.go
tester/test_data/config/node1/bitxhub.toml
tester/test_data/config/node2/bitxhub.toml
tester/test_data/config/node3/bitxhub.toml
tester/test_data/config/node4/bitxhub.toml

Revert "feat(*): improve governance"

---

README.md
cmd/bitxhub/client/appchain_manage.go
cmd/bitxhub/client/governance.go
cmd/bitxhub/client/rule_manage.go
config/bitxhub.toml
go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/governance.go
internal/executor/contracts/role.go
internal/executor/contracts/role_test.go
internal/executor/contracts/rule_manager.go
internal/executor/contracts/rule_manager_test.go
pkg/peermgr/testdata/network.toml
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case006_vote_test.go
tester/test_data/config/node1/bitxhub.toml
tester/test_data/config/node2/bitxhub.toml
tester/test_data/config/node3/bitxhub.toml
tester/test_data/config/node4/bitxhub.toml

1. Updating application chain basic information does not require governance;
2. Add validation rule register;
3. Add default validation rules to the application chain of type Fabric;
4. Add update master rule;
5. Change governance receipt from proposal id to GovernanceResult;
6. Add super admin in governance.

feat(*): improve governance

---

docs/docs/bitxhub/usage/deploy_bitxhub.md

docs(*):modify bitxhub deploy doc

---

go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/role.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case006_vote_test.go
tester/tester_test.go

1. Add GetIdByAddr to appchain_manager.go;
2. Fix some bugs in integration test.

feat(*): add GetIdByAddr to appchain_manager.go

---

pkg/order/etcdraft/node.go
pkg/order/etcdraft/util.go

1. fix index bug if syncing block is not finished
2. set seqNo if leader is just elected

fix: 2 raft bugs

---

scripts/cluster.sh

fix the "Start bitxhub fail" error for issue 480

bug fix for issue 480: start script failed

---

config/bitxhub.toml
internal/app/bitxhub.go
internal/executor/executor.go
internal/executor/oracle/appchain/eth.go
internal/repo/config.go
pkg/vm/boltvm/register.go

(cherry picked from commit 0d1fa20f1852ef50e2a25cbe39801fc34d5c8901)

fix:fix load eth header json file

---

cmd/bitxhub/client/governance.go
cmd/bitxhub/client/node_manage.go
cmd/bitxhub/client/role_manage.go
internal/executor/contracts/governance.go
internal/executor/contracts/governance_test.go
internal/executor/contracts/node_manager.go
internal/executor/contracts/node_manager_test.go
internal/executor/contracts/role.go

1.Allows the proposal sponsor administrator and the proposal related administrator to vote;
2.Add the list of administrators to vote on in the proposal;
3.Fix the bug that the audit administrator failed to query the information after updating the audit node.

fix(*): improve voting logic

---

.github/workflows/release.yml
Dockerfile
Dockerfile-raft
Dockerfile-solo
Dockerfile.solo
scripts/release_binary.sh

update github action and release scripts

update github action and release scripts

---

goent.diff

fix the timeStamp
fix the initialization of getPendingNonce

fix(rbft): fix the bug of rbft.

---

cmd/bitxhub/client/appchain_manage.go
cmd/bitxhub/client/governance.go
cmd/bitxhub/client/node_manage.go
cmd/bitxhub/client/role_manage.go
cmd/bitxhub/client/rule_manage.go
go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/governance.go
internal/executor/contracts/governance_test.go
internal/executor/contracts/interchain.go
internal/executor/contracts/interchain_test.go
internal/executor/contracts/node_manager.go
internal/executor/contracts/node_manager_test.go
internal/executor/contracts/role.go
internal/executor/contracts/role_test.go
internal/executor/contracts/rule_manager.go
internal/executor/contracts/rule_manager_test.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case006_vote_test.go

1. Add an active freeze that does not require voting governance;
2. Improve the availability of appchain(freezing、logouting are also available states);
3. Fixed a bug where the frozen state of the app chain could be updated.

fix(*): improve appchain management

---

go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/governance.go

1. Improve interface for determining the available status of appchain;
2. Update bitxhub-core version.

fix(*): improve interface for determining the available status of appchain

---

internal/executor/contracts/interchain.go
internal/executor/contracts/service_manager.go

1. Fix an error judgment bug when querying services
2. Add its own serviceKey method to the Interchain contract

fix(contracts): fix get service error

---

cmd/bitxhub/client/governance.go
go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/dapp_manager.go
internal/executor/contracts/governance.go
internal/executor/contracts/governance_test.go
internal/executor/contracts/node_manager.go
internal/executor/contracts/role.go
internal/executor/contracts/role_test.go
internal/executor/contracts/rule_manager.go
internal/executor/contracts/rule_manager_test.go
internal/executor/contracts/service_manager.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case006_vote_test.go
tester/case007_rule_test.go
tester/case008_service_test.go

1.Fix a bug where the rule did not enter binding state when registering the appchain;
2.Fix a bug where appchain could be activated during rule update;
3.Fix a bug where the rule proposal was not paused when the appchain was unregistered;
4.Fix spelling errors in "appove" and "updata".

fix(bvm): fix bug about rule and apchain manage

---

cmd/bitxhub/client/dapp_manage.go
cmd/bitxhub/client/governance.go
go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/appchain_manager_test.go
internal/executor/contracts/dapp_manager.go
internal/executor/contracts/dapp_manager_test.go
internal/executor/contracts/governance.go
internal/executor/contracts/governance_test.go
internal/executor/contracts/node_manager.go
internal/executor/contracts/role.go
internal/executor/contracts/role_test.go
internal/executor/executor.go
pkg/peermgr/testdata/network.toml
pkg/vm/boltvm/boltvm.go
tester/case002_appchain_test.go
tester/case003_interchain_test.go
tester/case004_role_test.go
tester/case006_vote_test.go

1. Add dapp mgr contract and cmd;
2. Fix appoved spelling errors.

feat(*): add dapp mgr

---

cmd/bitxhub/client/dapp_manage.go
internal/executor/contracts/dapp_manager.go
internal/executor/contracts/dapp_manager_test.go

1. add url to dapp
2. fix dapp update cmd error

fix(*): add url to dapp

---

go.mod
go.sum
internal/executor/contracts/dapp_manager.go

Add transferred status and change the status to transferred if the owner is not you when querying your own Dapp list

fix(contracts): fix a bug where the status of self dapp is not correct

---

internal/executor/contracts/dapp_manager.go

When querying the owner's list of dapps, place the transferred dapp at the end of the list

fix(ocntract): sort dapp list when get owner dapps

---

internal/executor/contracts/dapp_manager.go
internal/executor/contracts/dapp_manager_test.go

1. Fix invalid DAPP contract address update bug
2. Fix a bug where dAPP contract address could be updated to someone else's contract address

fix(ocntract): fix update dapp contract error

---

internal/executor/contracts/interchain.go
internal/executor/contracts/interchain_test.go
tester/case003_interchain_test.go

1. Add unit tests for interchain contract;
2. Delete redundant duplicate method Interchain from interchain.

test(contracts): add unit tests for interchain contract

---

api/grpc/subscribe_audit.go
go.mod
go.sum
internal/coreapi/audit.go
internal/executor/handle.go
internal/ledger/evmstate_accessor.go
pkg/utils/utils.go
tester/tester_test.go

1. Fix the bug that the audit interface fails to obtain data due to channel blocking;
2. Use Bloom to optimize the process for filtering transactions that contain audit information.

[WIP]fix(*): fix the bug that the audit interface could not get data

---

api/grpc/subscribe_audit.go
go.mod
go.sum
internal/coreapi/audit.go
internal/executor/handle.go
internal/ledger/evmstate_accessor.go
pkg/utils/utils.go
tester/tester_test.go

1. Fix the bug that the audit interface fails to obtain data due to channel blocking;
2. Use Bloom to optimize the process for filtering transactions that contain audit information.

fix(*): fix the bug that the audit interface could not get data

---

go.mod
go.sum
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/role.go
internal/executor/contracts/service_manager.go

1. Fix a bug where the address was occupied when updating the appchain administrator;
2. Fix a bug where the service ID format is incorrect when registering the Fabric chain service.

fix(contracts): fix update appchain admin error

---

cmd/bitxhub/client/node_manage.go
cmd/bitxhub/client/role_manage.go
internal/executor/contracts/role.go

1. Add bind role cmd;
2. Fix a parameter bug in register role cmd;
3. Fix parameter type bug in node cmd.

fix(cmd): add bind role cmd

---

go.mod
go.sum
internal/executor/contracts/node_manager.go
internal/executor/contracts/node_manager_test.go

Bitxhub-core needs to be merged first: meshplus/bitxhub-core#136

fix(contracts): update the method of checking vp node id

---

go.mod
go.sum
internal/executor/contracts/proposal_strategy.go
internal/executor/contracts/proposal_strategy_test.go
internal/repo/repo.go

1. Fix a bug where module strategy status was not checked when global strategy updates were made;
2. Fix a bug where incorrect module name "allmgr" may be passed when updating module policy.

fix(*): fix a bug where module strategy status was not checked when global strategy updates were made

---

api/grpc/broker.go
cmd/bitxhub/cert.go
cmd/bitxhub/client/client.go
cmd/bitxhub/client/governance.go
cmd/bitxhub/client/node.go
cmd/bitxhub/client/role_manage.go
config/bitxhub.toml
go.mod
internal/executor/contracts/appchain_manager.go
internal/executor/contracts/governance.go
internal/executor/contracts/governance_test.go
internal/executor/contracts/proposal_strategy.go
internal/executor/contracts/proposal_strategy_test.go
internal/executor/contracts/role.go
internal/ledger/genesis/genesis.go
internal/repo/config.go
internal/repo/repo.go
internal/repo/testdata/bitxhub.toml
tester/case006_vote_test.go
tester/case007_rule_test.go
tester/case008_service_test.go

1. Use strategy formula as the decision-making condition of proposal strategy;
2. Fix some bugs of commands.

fix(*): fix the bug where the proposal strategy was not reasonable

---

go.mod
go.sum

- fix the viewChange bug during rbft sync state when stopping other nodes

modify p2p pool to sync map

---

config/order.toml
goent.diff
pkg/order/etcdraft/config.go
pkg/order/etcdraft/node.go
pkg/order/etcdraft/node_util_test.go
pkg/order/etcdraft/util.go
pkg/order/mempool/mempool.go
pkg/order/mempool/mempool_impl.go
pkg/order/mempool/mempool_test.go
pkg/order/mempool/tx_store.go
pkg/peermgr/testdata/network.toml

support to delete transactions that have existed in the mempool for too long

feat(raft): support to delete alived transactions in mempool

---

goent.diff
pkg/order/etcdraft/node.go
pkg/order/mempool/mempool_impl.go

fix(rbft):start removeTxsTimer

fix(rbft):read ToleranceRemoveTime config

---

api/grpc/pier_monitor.go
api/grpc/receipt.go
api/grpc/sign.go
go.mod
go.sum
internal/app/bitxhub.go
internal/app/feedhub.go
internal/coreapi/api/api.go
internal/coreapi/broker.go
pkg/peermgr/handle.go
pkg/utils/utils.go

1. Fix an issue that failed to request signature from a not tss node;
2. Add code review todos.

fix(*): req to non tss node

---

api/grpc/sign.go
config/bitxhub.toml
go.mod
go.sum
internal/app/bitxhub.go
pkg/peermgr/handle.go
pkg/utils/utils.go

1. Fix the bug of tss signature verification failure;
2. Fix the bug that TSS priv key will not be re-created after a creation failure.

fix(*): Fix the bug of tss signature verification failure

---

api/grpc/transaction.go
internal/coreapi/feed.go
internal/executor/contracts/interchain.go
internal/executor/contracts/interchain_test.go
internal/executor/contracts/service_manager.go
internal/executor/contracts/service_manager_test.go
internal/executor/executor.go
internal/executor/executor_test.go
internal/executor/handle.go
internal/executor/types.go
pkg/vm/boltvm/boltvm.go
pkg/vm/boltvm/boltvm_test.go

feat: support remote subscribeBlock api

feat: modify checkServiceAbility

---

goent.diff
internal/executor/executor_test.go
internal/executor/handle.go
pkg/peermgr/handle.go

support automatic rollback  when malicious node block fork

feat: add ledger rollback function

---

api/jsonrpc/namespaces/eth/api.go

feat: support the option of evmMaxCodeSize
